version: '3.7'

services:
  nginx:
    build:
      dockerfile: dev-nginx.Dockerfile
      context: ./nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - api
      - frontend
  
  frontend:
    build:
      dockerfile: dev-npm.Dockerfile
      context: ./nginx
    ports: 
      - 8080:8080
    restart: always
    volumes:
      - /app/node_modules
      - /app/dist
      - ./nginx/frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Trololo124!
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Trololo124!
    depends_on:
      - mongo

  auth:
    build:
      dockerfile: dev.Dockerfile
      context: ./auth
    restart: always
    ports:
      - 5001:80
    volumes:
      - ./auth/app:/app
    depends_on:
      - mongo
    environment:
      - MONGO=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=Trololo124!

  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./api
    ports:
      - 5000:80
    restart: always
    volumes:
      - ./api/app:/app
    depends_on: 
      - mongo
      - auth
    environment:
      - MONGO=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=Trololo124!
      - AUTH_SERVER=auth

  

volumes:
  mongodb: {}