version: "3.7"

services:
  nginx:
    build:
      dockerfile: dev-nginx.Dockerfile
      context: ./nginx
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - api
      - frontend
      - translator

  frontend:
    build:
      dockerfile: dev-nuxt.Dockerfile
      context: ./nuxt-app
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./nuxt-app/assets/:/app/assets
      - ./nuxt-app/components/:/app/components
      - ./nuxt-app/layouts/:/app/layouts
      - ./nuxt-app/middleware/:/app/middleware
      - ./nuxt-app/pages/:/app/pages
      - ./nuxt-app/plugins/:/app/plugins
      - ./nuxt-app/static/:/app/static
      - ./nuxt-app/store/:/app/store
      - ./nuxt-app/jsonconfig.json:/app/jsonconfig.json
      - ./nuxt-app/nuxt.config.js:/app/nuxt.config.js
      - ./nuxt-app/package-lock.json:/app/package-lock.json
      - ./nuxt-app/package.json:/app/package.json

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Trololo124!
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Trololo124!
    depends_on:
      - mongo

  auth:
    build:
      dockerfile: dev.Dockerfile
      context: ./auth
    restart: on-failure
    ports:
      - 5001:80
    volumes:
      - ./auth/app:/app
    depends_on:
      - mongo
    environment:
      - MONGO=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=Trololo124!

  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./api
    ports:
      - 5000:80
    restart: on-failure
    volumes:
      - ./api/app:/app
    depends_on:
      - mongo
      - auth
    environment:
      - MONGO=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=Trololo124!

  translator:
    build:
      dockerfile: dev.Dockerfile
      context: ./edge-JWT-translator
    restart: on-failure
    ports:
      - 5002:80
    volumes:
      - ./edge-JWT-translator/app:/app
    depends_on:
      - mongo
    environment:
      - MONGO=mongo
      - MONGO_USER=admin
      - MONGO_PASSWORD=Trololo124!

volumes:
  mongodb: {}
